### ISSUE TITLE
HTTPS settings

### ISSUE THREAD

**Issue by heba29** [jaylagorio/Nightscout-on-Windows-Server#1]
Hello, I have successfully completed the manual. Thank you very much for that. Now I want to change the port from 80 to 443. Do I have to call the nightscout setup again? Or where do I change the parameters?

**Comment by jaylagorio** [comment]
Sorry for the late response. Are you using IIS in front of the Node server or are you accessing Nightscout directly without using IIS?

**Comment by heba29** [comment]
Hello, without IIS.

Grüße Herbert

Am 20.02.2019 um 20:11 schrieb jaylagorio <notifications@github.com<mailto:notifications@github.com>>:


Sorry for the late response. Are you using IIS in front of the Node server or are you accessing Nightscout directly without using IIS?

**Comment by jaylagorio** [comment]
It's not clear to me that you can use Nightscout over SSL without changing the code, but I could be wrong. What I recommend is following the instructions to put IIS in front of Node, then using IIS as the SSL provider. You can do that by getting a certificate and installing it in IIS, making sure the Site is using port 443. Then the connection to Nightscout would look like this:

Web Browser or OpenAPS -> HTTPS to IIS -> HTTP to Node

Because the IIS and Node services live on the same server it's OK that they communicate without encryption because the traffic doesn't leave the server.

**Comment by heba29** [comment]
Ok. I wil try it next time. Thank you

Grüße Herbert

Am 20.02.2019 um 20:18 schrieb jaylagorio <notifications@github.com<mailto:notifications@github.com>>:


It's not clear to me that you can use Nightscout over SSL without changing the code, but I could be wrong. What I recommend is following the instructions to put IIS in front of Node, then using IIS as the SSL provider. You can do that by getting a certificate and installing it in IIS, making sure the Site is using port 443. Then the connection to Nightscout would look like this:

Web Browser or OpenAPS -> HTTPS to IIS -> HTTP to Node

Because the IIS and Node services live on the same server it's OK that they communicate without encryption because the traffic doesn't leave the server.
