### ISSUE TITLE
Is the instruction for the version nightscout 0.11.1 relevant?

### ISSUE THREAD

**Issue by Alloho** [jaylagorio/Nightscout-on-Windows-Server#2]
Good day.
I installing my server, according to your instructions. But after starting the node server, the web page (http://localhost) is not available. Is this manual relevant for version nightscout 0.11.1 or do need to make any changes?

**Comment by jaylagorio** [comment]
I haven't had a chance to look at Nightscout 0.11.1 yet so I can't tell you for sure. Do you have logs from the Nightscout console window? If you have Nightscout running via Task Scheduler you'll want to end that running task, then from a command prompt in the Nightscout directory you'll type:

``node server.js``

**Comment by jaylagorio** [comment]
Additionally, note that the Node port I recommended is 81, so try accessing it via http://localhost:81/

**Comment by Alloho** [comment]
it's all because of the redirect to https
It worked only after setting set INSECURE_USE_HTTP to true

**Comment by jaylagorio** [comment]
Looks like I need to update the Node version (minimum LTS 10.15.1) and add the `INSECURE_USE_HTTP` environment variable to the setup instructions. It also looks like I need to be clearer in the IIS portion of the documentation that the `PORT` environment variable needs to be changed if you're using IIS in front of it on the same server because otherwise one service will try to step on the other. Thanks for documenting this!

**Comment by jaylagorio** [comment]
Addressed for 0.12.5 and online now.
